DROP DATABASE IF EXISTS profile_db;

CREATE DATABASE profile_db;

USE profile_db;

CREATE TABLE posts (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE projects (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  image BLOB,
  imageName VARCHAR(255),
  website VARCHAR(255) NOT NULL,
  github VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);